name: PNPM update -> PR

on:
  schedule:
    - cron: "0 9 * * *"   # 09:00 UTC
    - cron: "0 21 * * *"  # 21:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: pnpm-update
  cancel-in-progress: false

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Per pnpm docs: install pnpm first, then setup-node with cache
      # Omitting `version:` uses your package.json "packageManager": "pnpm@9.15.0"
      - name: Setup pnpm
        id: setup_pnpm
        continue-on-error: true
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Add pnpm to PATH
        id: pnpm_path
        continue-on-error: true
        run: echo "${{ steps.setup_pnpm.outputs.bin_dest }}" >> "$GITHUB_PATH"

      - name: Setup Node
        id: setup_node
        continue-on-error: true
        uses: actions/setup-node@v4
        with:
          node-version: 24.6.0
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps (frozen)
        id: install
        continue-on-error: true
        run: pnpm install --frozen-lockfile

      - name: Run pnpm update -L and capture logs
        id: run
        continue-on-error: true
        shell: bash
        run: |
          ts=$(date -u +'%Y-%m-%d_%H-%M-%S')   # filesystem-safe for artifact names
          echo "ts=$ts" >> "$GITHUB_OUTPUT"
          pnpm update -L 2>&1 | tee run.log
          ec=$?
          echo "exit_code=$ec" >> "$GITHUB_OUTPUT"

      - name: Detect changes
        id: changes
        continue-on-error: true
        shell: bash
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build package.json diff summary (exclude lockfile)
        id: pkgdiff
        continue-on-error: true
        shell: bash
        run: |
          files=$(git ls-files -m | grep -E '(^|/)package\.json$' || true)
          if [[ -z "$files" ]]; then
            echo "summary=No package.json changes." >> "$GITHUB_OUTPUT"
          else
            echo "summary<<EOF" >> "$GITHUB_OUTPUT"
            for f in $files; do
              echo "### $f"
              git --no-pager diff --unified=0 --no-color -- "$f" || true
              echo
            done
            echo "EOF" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload run log (artifact)
        id: artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-update-log-${{ steps.run.outputs.ts }}
          path: run.log
          if-no-files-found: warn

      - name: Assemble PR body
        id: prbody
        shell: bash
        run: |
          # AIDEV-NOTE: Build PR body content in output variable instead of temporary file
          {
            echo "body<<EOF"
            echo "Automated dependency update via \`pnpm update -L\`."
            echo ""
            echo "- Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            echo "- Log artifact: pnpm-update-log-${{ steps.run.outputs.ts }}"
            echo ""
            echo "**package.json diff summary**"
            echo "---"
            files=$(git diff --name-only | grep -E '(^|/)package\.json$' || true)
            if [ -z "$files" ]; then
              echo "No package.json changes."
            else
              for f in $files; do
                echo "### $f"
                git --no-pager diff --unified=0 --no-color -- "$f" || true
                echo
              done
            fi
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      # Create PR on success + changes using the default GITHUB_TOKEN
      - name: Create PR (GITHUB_TOKEN)
        id: cpr
        if: ${{ steps.changes.outputs.changed == 'true' && steps.run.outputs.exit_code == '0' }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps): update packages to latest"
          title: "chore(deps): update packages to latest"
          body: ${{ steps.prbody.outputs.body }}
          branch: chore/pnpm-update-${{ steps.run.outputs.ts }}
          delete-branch: true
          labels: |
            dependencies
            automated
          assignees: robahtou

      # Final: fail job if ANY critical step failed (keeps GitHub failure emails)
      - name: Mark job failed if any step failed
        if: always()
        run: |
          failed=0
          if [ "${{ steps.checkout.outcome }}"   = "failure" ]; then echo "::error::Step 'checkout' failed";   failed=1; fi
          if [ "${{ steps.setup_pnpm.outcome }}" = "failure" ]; then echo "::error::Step 'setup_pnpm' failed"; failed=1; fi
          if [ "${{ steps.pnpm_path.outcome }}"  = "failure" ]; then echo "::error::Step 'pnpm_path' failed";  failed=1; fi
          if [ "${{ steps.setup_node.outcome }}" = "failure" ]; then echo "::error::Step 'setup_node' failed"; failed=1; fi
          if [ "${{ steps.install.outcome }}"    = "failure" ]; then echo "::error::Step 'install' failed";    failed=1; fi
          if [ "${{ steps.run.outcome }}"        = "failure" ]; then echo "::error::Step 'run' failed";        failed=1; fi
          if [ "${{ steps.changes.outcome }}"    = "failure" ]; then echo "::error::Step 'changes' failed";    failed=1; fi
          if [ "${{ steps.pkgdiff.outcome }}"    = "failure" ]; then echo "::error::Step 'pkgdiff' failed";    failed=1; fi
          if [ "${{ steps.artifact.outcome }}"   = "failure" ]; then echo "::error::Step 'artifact' failed";   failed=1; fi
          if [ "${{ steps.cpr.outcome }}"        = "failure" ]; then echo "::error::Step 'cpr' failed";        failed=1; fi
          if [ "${{ steps.run.outputs.exit_code }}" != "0" ]; then
            echo "::error::pnpm update -L failed with exit code ${{ steps.run.outputs.exit_code }}"
            failed=1
          fi
          if [ $failed -ne 0 ]; then exit 1; fi
