name: Lint PR titles (Conventional Commits)

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
            ci
            build
            perf
            revert
          requireScope: true
          scopes: |
            deps
            api
            ui
            db
            tooling
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
